--- 
- 
  hosts: all
- 
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  name: "Include dynamic variables"
  tags: 
    - always
  tasks: ~


-  hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- 
  hosts: mysql
- 
  import_playbook: ../static-assignments/db.yml
  name: "import databse file"
- 
  hosts: lb
- 
  import_playbook: ../static-assignments/loadbalancers.yml
  name: "Loadbalancers assignment\""
  when: load_balancer_is_required
