--- 
- 
  hosts: all
  name: "Include dynamic variables"
- 
  import_playbook: ../static-assignments/common.yml
  name: "import commor file"
  tags: 
    - always
- 
  import_playbook: ../dynamic-assignments/env-vars.yml
  name: "include env-vars file"
  tags: 
    - always
- 
  hosts: webservers
- 
  import_playbook: ../static-assignments/uat-webservers.yml
  name: "Webserver assignment"
- 
  hosts: mysql
  import_playbook: ../static-assignments/db.yml
  name: "import databaser file"
- 
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  name: "Loadbalancers assignment"
  when: load_balancer_is_required
